import 'dart:io';
import 'dart:math';
import 'dart:typed_data';

import 'package:breez_sdk/breez_sdk.dart';
import 'package:breez_sdk/sdk.dart';
import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';

/// Lightweight service wrapper for BreezSDK.
///
/// Usage:
/// - Call `await BreezeService.instance.init()` early (e.g. in main()) to
///   initialize logs/events stream and prepare working directory.
/// - Call `await BreezeService.instance.connect()` to actually connect the node.
class BreezeService {
  BreezeService._();
  static final BreezeService instance = BreezeService._();
  factory BreezeService() => instance;

  BreezSDK? _sdk;

  BreezSDK get _internalSdk => _sdk ??= BreezSDK();

  /// Initialize SDK event/log streams and ensure working directory exists.
  /// This does NOT connect the node; call [connect] to connect.
  Future<Directory> init({String subDirName = 'breez'}) async {
    final appDir = await getApplicationDocumentsDirectory();
    final workingDir = Directory('${appDir.path}/$subDirName');
    if (!await workingDir.exists()) {
      await workingDir.create(recursive: true);
    }

    // Initialize SDK streams (idempotent)
    final breez = _internalSdk;
    try {
      final initialized = await breez.isInitialized();
      if (!initialized) {
        // initialize only sets up sdk streams (events/logs). It's safe to call.
        breez.initialize();
      }
    } catch (e) {
      // If isInitialized throws, still call initialize to ensure streams are ready
      try {
        breez.initialize();
      } catch (_) {}
    }

    if (kDebugMode) debugPrint('BreezeService: workingDir=${workingDir.path}');
    return workingDir;
  }

  /// Connects the Breez node using an autogenerated seed (unless [seed] provided).
  ///
  /// Returns once `connect` completes. If you want to check node state after
  /// connect, call [isConnected] or [nodeInfo].
  Future<void> connect({
    Uint8List? seed,
    EnvironmentType envType = EnvironmentType.Staging,
    String apiKey = '',
    NodeConfig? nodeConfig,
    String? workingDirPath,
  }) async {
    final breez = _internalSdk;

    // Ensure streams are initialized and working dir exists
    final workingDir = workingDirPath == null
        ? (await init()).path
        : (await Directory(workingDirPath).create(recursive: true)).path;

    nodeConfig ??= NodeConfig.greenlight(config: GreenlightNodeConfig());

    // defaultConfig returns a Config which we tweak to set workingDir and network
    final baseConfig = await defaultConfig(
      envType: envType,
      apiKey: apiKey,
      nodeConfig: nodeConfig,
    );

    final config = baseConfig.copyWith(
      workingDir: workingDir,
      // keep config network value if present, otherwise set Testnet
      network: baseConfig.network,
    );

    final seedBytes = seed ?? _randomSeed32();

    await breez.connect(req: ConnectRequest(config: config, seed: seedBytes));

    if (kDebugMode) debugPrint('BreezeService: connect() completed');
  }

  /// Returns true if Breez node service is initialized (connected and ready).
  Future<bool> isConnected() async {
    final breez = _sdk ?? _internalSdk;
    try {
      return await breez.isInitialized();
    } catch (_) {
      return false;
    }
  }

  /// Fetch node information; useful to validate node state after connect.
  Future<NodeState?> nodeInfo() async {
    final breez = _sdk ?? _internalSdk;
    try {
      return await breez.nodeInfo();
    } catch (_) {
      return null;
    }
  }

  /// Exposes the underlying SDK instance (if needed).
  BreezSDK? get sdk => _sdk ?? _internalSdk;

  static Uint8List _randomSeed32() {
    final rnd = Random.secure();
    return Uint8List.fromList(List<int>.generate(32, (_) => rnd.nextInt(256)));
  }
}
