// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD0qLLTmo2OAgRmdZ8at0-tR6tZf2bLXA',
    appId: '1:51444009038:web:ee0c19ce3a83ffb2fcdb1f',
    messagingSenderId: '51444009038',
    projectId: 'lightningpay-13df6',
    authDomain: 'lightningpay-13df6.firebaseapp.com',
    storageBucket: 'lightningpay-13df6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB334-u1KCw9BNcJRyZLy4SlNYFMji0oIQ',
    appId: '1:51444009038:android:b3c4c971e5971e5ffcdb1f',
    messagingSenderId: '51444009038',
    projectId: 'lightningpay-13df6',
    storageBucket: 'lightningpay-13df6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMsXAoFWe6eQPnkQcVCEMHszQHhUpd8Mk',
    appId: '1:51444009038:ios:88a9def4e4fb9b5cfcdb1f',
    messagingSenderId: '51444009038',
    projectId: 'lightningpay-13df6',
    storageBucket: 'lightningpay-13df6.firebasestorage.app',
    iosBundleId: 'com.example.lightingPay',
  );
}
